name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Install xmlstarlet
      run: |
        sudo apt-get update
        sudo apt-get install xmlstarlet
        
    - name: Get current version number
      id: get_version
      run: echo "::set-output name=version::$(xml sel -t -v '//Project/PropertyGroup/Version' TdInterface/TdInterface.csproj)"
      
    - name: Increment version number
      id: increment_version
      run: echo "::set-output name=version::$(echo ${{ steps.get_version.outputs.version }} | awk -F. '{$NF = $NF + 1;} 1' OFS=. )"
      
    - name: Update version number
      run: xml ed -L -N msbuild -u '//msbuild:Project/msbuild:PropertyGroup/msbuild:Version' -v "${{ steps.increment_version.outputs.version }}" TdInterface/TdInterface.csproj
      
    - name: Build
      run: dotnet build --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish
      
#    - name: Get next version
#      uses: reecetech/version-increment@2022.5.1
#      id: version
#      with:
#        scheme: semver
#        increment: patch      

    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        type: 'zip'
        filename: "TDInterface.zip"
        directory: 'D:\a\TDInterface-Public\TDInterface-Public\TdInterface\bin\Debug\net7.0-windows\publish\'
        
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: 'D:\a\TDInterface-Public\TDInterface-Public\TdInterface\bin\Debug\net7.0-windows\publish\TDInterface.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: "newver"

